export type CaptionLanguage = {
  code: string;
  name: string;
  isAutoGenerated: boolean;
};

type CaptionTrack = {
  baseUrl: string;
  languageCode: string;
  name?: {
    simpleText?: string;
    runs?: Array<{ text: string }>;
  };
  kind?: string;
};

export async function listYouTubeCaptionLanguages(videoId: string): Promise<CaptionLanguage[]> {
  const response = await fetch(`https://www.youtube.com/watch?v=${videoId}`, {
    headers: {
      "Accept-Language": "en-US,en;q=0.8",
      "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"
    }
  });

  const html = await response.text();
  const playerResponse = parseInlineJson(html, "ytInitialPlayerResponse");
  const tracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;

  if (!Array.isArray(tracks)) {
    return [];
  }

  const unique = new Map<string, CaptionLanguage>();
  for (const track of tracks as CaptionTrack[]) {
    const name = track.name?.simpleText ?? track.name?.runs?.map((run) => run.text).join("") ?? track.languageCode;
    unique.set(track.languageCode, {
      code: track.languageCode,
      name,
      isAutoGenerated: track.kind === "asr"
    });
  }

  return [...unique.values()];
}

function parseInlineJson(html: string, globalName: string) {
  const startToken = `var ${globalName} = `;
  const startIndex = html.indexOf(startToken);
  if (startIndex === -1) {
    return null;
  }

  const jsonStart = startIndex + startToken.length;
  let depth = 0;
  for (let index = jsonStart; index < html.length; index += 1) {
    const char = html[index];
    if (char === "{") {
      depth += 1;
    } else if (char === "}") {
      depth -= 1;
      if (depth === 0) {
        try {
          return JSON.parse(html.slice(jsonStart, index + 1));
        } catch {
          return null;
        }
      }
    }
  }

  return null;
}
