"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  Bell,
  Captions,
  CheckCircle2,
  Download,
  ExternalLink,
  Film,
  FolderOpen,
  Heart,
  Wand2,
  LogIn,
  LogOut,
  Menu,
  Mic,
  Send,
  Search,
  ShieldCheck,
  Upload,
  User,
  UserPlus,
  XCircle
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { CreatorPanel } from "@/components/learn/CreatorPanel";
import { LyricTimeline } from "@/components/learn/LyricTimeline";
import { LyricsDownload } from "@/components/learn/LyricsDownload";
import { LyricsScroller } from "@/components/learn/LyricsScroller";
import { PlaybackControls } from "@/components/learn/PlaybackControls";
import { VideoSurface } from "@/components/learn/VideoSurface";
import { completedSongVideos, type SongVideo } from "@/lib/catalog";
import { parseEditableLrcText, parseSubtitleText } from "@/lib/subtitles";
import { resolveVideoInput, type ResolvedVideo } from "@/lib/video-platforms";
import { cn } from "@/lib/utils";
import { usePlayerStore } from "@/store/player-store";
import type { LyricLine, ParsedLyrics } from "@/types/lyrics";

type CaptionLanguage = {
  code: string;
  name: string;
  isAutoGenerated: boolean;
};

type UserSession = {
  id: string;
  displayName: string;
  email: string;
  role: "user" | "admin";
  avatarUrl: string | null;
};

type UiLanguage = "zh" | "en";

const COPY = {
  zh: {
    searchPlaceholder: "搜索本站已制作的学歌视频",
    create: "创作",
    login: "登录",
    profile: "个人主页",
    myCreations: "我的创作",
    myFavorites: "我的收藏",
    review: "审核",
    logout: "退出登录",
    source: "视频出处",
    lyrics: "滚动歌词",
    comments: "评论区",
    download: "下载歌词",
    format: "导出格式",
    createMode: "创作模式",
    songTitle: "歌曲名字",
    artist: "歌手 / 作者",
    language: "语言",
    description: "简介",
    noResults: "站内暂时没有匹配的制作完成视频。",
    sourceUrl: "粘贴 YouTube / Bilibili 视频链接",
    calibrationPreview: "校准预览",
    submitReview: "提交审核",
    submitSavedVersion: "提交的是上方已保存预览版本。",
    siteSongs: "站内学歌视频",
    account: "账户",
    loginRegister: "登录 / 注册",
    noCreations: "还没有创作条目。",
    favoritesEmpty: "收藏功能入口已预留。",
    profileHint: "登录后可以管理自己的制作草稿、提交记录和收藏歌曲。",
    adminOnly: "只有管理员可以进入审核界面。使用 admin123 / 123 登录。",
    adminReview: "管理员审核",
    noPending: "暂无待审核歌曲。",
    edit: "编辑",
    reject: "拒绝",
    approve: "通过",
    sourceVideo: "加载视频源",
    fetchCaptions: "抓取字幕",
    fetching: "抓取中",
    autoAlign: "自动校准",
    aligning: "校准中",
    submitForReview: "提交审核"
  },
  en: {
    searchPlaceholder: "Search finished song lessons",
    create: "Create",
    login: "Login",
    profile: "Profile",
    myCreations: "My Creations",
    myFavorites: "My Favorites",
    review: "Review",
    logout: "Log out",
    source: "Source",
    lyrics: "Scrolling Lyrics",
    comments: "Comments",
    download: "Download lyrics",
    format: "Export",
    createMode: "Create Mode",
    songTitle: "Song title",
    artist: "Artist",
    language: "Language",
    description: "Description",
    noResults: "No finished song lesson matches this search.",
    sourceUrl: "Paste YouTube / Bilibili source URL",
    calibrationPreview: "Calibration Preview",
    submitReview: "Submit for Review",
    submitSavedVersion: "Submits the saved preview version above.",
    siteSongs: "Song Lessons",
    account: "Account",
    loginRegister: "Login / Register",
    noCreations: "No creations yet.",
    favoritesEmpty: "Favorites are reserved for the next step.",
    profileHint: "Log in to manage drafts, submissions, and saved songs.",
    adminOnly: "Only admins can enter review. Log in with admin123 / 123.",
    adminReview: "Admin Review",
    noPending: "No pending songs.",
    edit: "Edit",
    reject: "Reject",
    approve: "Approve",
    sourceVideo: "Load source",
    fetchCaptions: "Fetch captions",
    fetching: "Fetching",
    autoAlign: "Auto Align",
    aligning: "Aligning",
    submitForReview: "Submit for review"
  }
} satisfies Record<UiLanguage, Record<string, string>>;

type CreationMeta = {
  title: string;
  artist: string;
  language: string;
  description: string;
};

type CreationEntry = {
  id: string;
  meta: CreationMeta;
  sourceUrl: string;
  video: ResolvedVideo;
  lyrics: ParsedLyrics;
  status: "draft" | "pending" | "approved" | "rejected";
  updatedAt: string;
};

export function LearnStudio() {
  const [activeSong, setActiveSong] = useState<SongVideo>(() => completedSongVideos[0]);
  const [searchQuery, setSearchQuery] = useState("");
  const [searchResults, setSearchResults] = useState<SongVideo[]>(completedSongVideos);
  const [createVideoUrl, setCreateVideoUrl] = useState("");
  const [createVideo, setCreateVideo] = useState<ResolvedVideo | null>(null);
  const [createMeta, setCreateMeta] = useState<CreationMeta>({
    title: "",
    artist: "",
    language: "",
    description: ""
  });
  const [subtitleText, setSubtitleText] = useState("");
  const [draftLyrics, setDraftLyrics] = useState<ParsedLyrics>(() => completedSongVideos[0].lyrics);
  const [editorLyrics, setEditorLyrics] = useState<ParsedLyrics>(() => completedSongVideos[0].lyrics);
  const [captionLanguages, setCaptionLanguages] = useState<CaptionLanguage[]>([]);
  const [subtitleLang, setSubtitleLang] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [isFetchingLanguages, setIsFetchingLanguages] = useState(false);
  const [isFetchingSubtitles, setIsFetchingSubtitles] = useState(false);
  const [isAutoAligning, setIsAutoAligning] = useState(false);
  const [activeWorkspace, setActiveWorkspace] = useState<
    "watch" | "create" | "admin" | "profile" | "auth" | "my-creations" | "favorites"
  >("watch");
  const [authMode, setAuthMode] = useState<"login" | "register">("login");
  const [session, setSession] = useState<UserSession | null>(null);
  const [myCreations, setMyCreations] = useState<CreationEntry[]>([]);
  const [favoriteIds] = useState<string[]>([]);
  const [isUserMenuOpen, setIsUserMenuOpen] = useState(false);
  const [uiLanguage, setUiLanguage] = useState<UiLanguage>("zh");
  const playerRef = useRef<YT.Player | null>(null);
  const copy = COPY[uiLanguage];

  const currentTime = usePlayerStore((state) => state.currentTime);
  const playerDuration = usePlayerStore((state) => state.duration);
  const isPlaying = usePlayerStore((state) => state.isPlaying);
  const isLoopingLine = usePlayerStore((state) => state.isLoopingLine);
  const setActiveLineId = usePlayerStore((state) => state.setActiveLineId);
  const setCurrentTime = usePlayerStore((state) => state.setCurrentTime);
  const setPlaybackRate = usePlayerStore((state) => state.setPlaybackRate);

  const visibleLyrics = activeWorkspace === "create" ? draftLyrics : activeSong.lyrics;
  const visibleVideo = activeWorkspace === "create" ? createVideo : activeSong.video;
  const activeLine = useMemo(
    () => findActiveLine(visibleLyrics.lines, currentTime),
    [currentTime, visibleLyrics.lines]
  );
  const canControlPlayer = visibleVideo?.platform === "youtube";

  const chooseSong = (song: SongVideo) => {
    playerRef.current = null;
    setActiveSong(song);
    setActiveWorkspace("watch");
    setCurrentTime(0);
    setError(null);
    setNotice(null);
  };

  const searchSongs = async () => {
    const response = await fetch(`/api/songs?q=${encodeURIComponent(searchQuery)}`);
    const payload = (await response.json()) as { songs: SongVideo[] };
    const ownSongs = myCreations
      .filter((creation) =>
        [creation.meta.title, creation.meta.artist, creation.meta.language]
          .join(" ")
          .toLowerCase()
          .includes(searchQuery.trim().toLowerCase())
      )
      .map(creationToSong);
    const songs = [...ownSongs, ...payload.songs];
    setSearchResults(songs);

    if (songs[0]) {
      chooseSong(songs[0]);
    } else {
      setNotice("站内还没有制作完成的匹配歌曲，可以去创作模式提交一个。");
    }
  };

  const listCaptionLanguages = useCallback(async (youtubeVideoId?: string) => {
    if (!youtubeVideoId) {
      return;
    }

    setIsFetchingLanguages(true);
    try {
      const response = await fetch(`/api/videos/${youtubeVideoId}/subtitles?list=1`);
      const payload = (await response.json()) as { languages?: CaptionLanguage[] };
      const languages = payload.languages ?? [];
      setCaptionLanguages(languages);
      setSubtitleLang(languages[0]?.code ?? "");
    } catch {
      setCaptionLanguages([]);
    } finally {
      setIsFetchingLanguages(false);
    }
  }, []);

  const loadCreateVideo = () => {
    const resolved = resolveVideoInput(createVideoUrl);
    if (!resolved) {
      setError("请输入有效的 YouTube 或 Bilibili 链接。");
      return;
    }

    playerRef.current = null;
    setCreateVideo(resolved);
    setDraftLyrics({ source: "user", lines: [] });
    setEditorLyrics({ source: "user", lines: [] });
    setSubtitleText("");
    setCurrentTime(0);
    setCaptionLanguages([]);
    setSubtitleLang("");
    setError(null);
    setNotice(resolved.platform === "bilibili" ? "Bilibili 创作模式已加载，歌词请上传或手动粘贴。" : null);

    if (resolved.platform === "youtube") {
      void listCaptionLanguages(resolved.videoId);
    }
  };

  const editCreation = (creation: CreationEntry) => {
    playerRef.current = null;
    setCreateVideo(creation.video);
    setCreateVideoUrl(creation.sourceUrl);
    setCreateMeta(creation.meta);
    setDraftLyrics(creation.lyrics);
    setEditorLyrics(creation.lyrics);
    setSubtitleText(toLrcText(creation.lyrics.lines));
    setActiveWorkspace("create");
    setNotice("已打开创作条目，可以继续编辑。");
  };

  const importLyrics = () => {
    const parsed = parseSubtitleText(subtitleText);
    if (parsed.lines.length === 0) {
      setError("没有解析到带时间戳的歌词。支持 LRC、SRT、WebVTT。");
      return;
    }

    setError(null);
    setEditorLyrics(parsed);
    playerRef.current?.seekTo(parsed.lines[0].startTime, true);
  };

  const fetchYouTubeSubtitles = async () => {
    if (!createVideo || createVideo.platform !== "youtube") {
      setError("自动抓字幕只在创作模式下支持 YouTube；Bilibili 请上传歌词。");
      return;
    }

    setIsFetchingSubtitles(true);
    setError(null);

    try {
      const query = subtitleLang ? `?lang=${subtitleLang}` : "";
      const response = await fetch(`/api/videos/${createVideo.videoId}/subtitles${query}`);
      const payload = await response.json();

      if (!response.ok) {
        throw new Error(payload.message ?? "抓不到这个视频的字幕。");
      }

      setEditorLyrics(payload);
      setSubtitleText(toLrcText(payload.lines));
      playerRef.current?.seekTo(payload.lines[0]?.startTime ?? 0, true);
    } catch (fetchError) {
      setError(
        fetchError instanceof Error
          ? `${fetchError.message} 可以改用上传 LRC / SRT / WebVTT。`
          : "抓不到这个视频的字幕，可以改用上传 LRC / SRT / WebVTT。"
      );
    } finally {
      setIsFetchingSubtitles(false);
    }
  };

  const autoAlign = async () => {
    if (editorLyrics.lines.length === 0 && !subtitleText.trim()) {
      setError("请先导入或粘贴歌词，再运行自动校准。");
      return;
    }

    setIsAutoAligning(true);
    setError(null);
    setNotice(null);

    try {
      const response = await fetch("/api/alignment/jobs", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          platform: createVideo?.platform,
          videoId: createVideo?.videoId,
          lyrics: editorLyrics,
          lyricsText: subtitleText
        })
      });
      const job = await response.json();

      if (!response.ok || job.status !== "completed" || !job.result) {
        throw new Error(job.message ?? "自动校准失败。");
      }

      setEditorLyrics(job.result);
      setSubtitleText(toLrcText(job.result.lines));
      setNotice("AI 自动校准已生成，可继续逐词微调后 Save。");
    } catch (alignError) {
      setError(alignError instanceof Error ? alignError.message : "自动校准失败。");
    } finally {
      setIsAutoAligning(false);
    }
  };

  const seekTo = useCallback((time: number) => {
    if (!canControlPlayer) {
      setCurrentTime(time);
      return;
    }

    playerRef.current?.seekTo(time, true);
    setCurrentTime(time);
  }, [canControlPlayer, setCurrentTime]);

  const replayLine = () => {
    if (activeLine && canControlPlayer) {
      seekTo(activeLine.startTime);
      playerRef.current?.playVideo();
    }
  };

  const changeRate = (rate: number) => {
    setPlaybackRate(rate);
    playerRef.current?.setPlaybackRate(rate);
  };

  const nudgeWordStart = (lineId: string, wordId: string, delta: number) => {
    setEditorLyrics((current) => ({
      ...current,
      lines: current.lines.map((line) => (line.id === lineId ? shiftWordTiming(line, wordId, delta) : line))
    }));
  };

  const nudgeWordDuration = (lineId: string, wordId: string, delta: number) => {
    setEditorLyrics((current) => ({
      ...current,
      lines: current.lines.map((line) => (line.id === lineId ? resizeWordDuration(line, wordId, delta) : line))
    }));
  };

  const changeLineStart = (lineId: string, startTime: number) => {
    setEditorLyrics((current) => {
      const next = {
        ...current,
        lines: current.lines.map((line) => (line.id === lineId ? moveLineToStart(line, startTime) : line))
      };
      setSubtitleText(toLrcText(next.lines));
      return next;
    });
  };

  const changeLineDuration = (lineId: string, duration: number) => {
    setEditorLyrics((current) => {
      const next = {
        ...current,
        lines: current.lines.map((line) => (line.id === lineId ? setLineDuration(line, duration) : line))
      };
      setSubtitleText(toLrcText(next.lines));
      return next;
    });
  };

  const insertLyricLine = (time: number) => {
    setEditorLyrics((current) => {
      const id = `line-${Date.now()}`;
      const nextLine = makeInsertedLine(id, time);
      const next = {
        ...current,
        lines: [...current.lines, nextLine].sort((a, b) => a.startTime - b.startTime)
      };
      setSubtitleText(toLrcText(next.lines));
      return next;
    });
  };

  const updateSubtitleText = (value: string) => {
    setSubtitleText(value);
    setEditorLyrics((current) => parseEditableLrcText(value, current.lines));
  };

  const deleteLyricLine = (lineId: string) => {
    setEditorLyrics((current) => {
      const next = {
        ...current,
        lines: current.lines.filter((line) => line.id !== lineId)
      };
      setSubtitleText(toLrcText(next.lines));
      return next;
    });
  };

  const nudgeAllLines = (delta: number) => {
    setEditorLyrics((current) => {
      const next = {
        ...current,
        lines: current.lines.map((line) => shiftLineTiming(line, delta))
      };
      setSubtitleText(toLrcText(next.lines));
      return next;
    });
  };

  const saveEditedLyrics = () => {
    if (!createVideo) {
      setError("请先加载视频源。");
      return;
    }

    const id = `${createVideo.platform}:${createVideo.videoId}`;
    const nextEntry: CreationEntry = {
      id,
      meta: normalizeMeta(createMeta, createVideo),
      sourceUrl: createVideoUrl,
      video: createVideo,
      lyrics: editorLyrics,
      status: "draft",
      updatedAt: new Date().toISOString()
    };

    setMyCreations((items) => [nextEntry, ...items.filter((item) => item.id !== id)]);
    setDraftLyrics(editorLyrics);
    setSubtitleText(toLrcText(editorLyrics.lines));
    setNotice("已保存到上方滚动歌词预览，也已加入我的创作。");
  };

  const submitLyrics = async () => {
    if (!session) {
      setActiveWorkspace("auth");
      setError("请先登录再提交歌词。");
      return;
    }

    if (!createVideo) {
      setError("请先在创作模式加载视频。");
      return;
    }

    await fetch("/api/submissions", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        userId: session.id,
        meta: normalizeMeta(createMeta, createVideo),
        platform: createVideo.platform,
        videoId: createVideo.videoId,
        lyrics: draftLyrics
      })
    });
    const id = `${createVideo.platform}:${createVideo.videoId}`;
    setMyCreations((items) =>
      items.map((item) => (item.id === id ? { ...item, status: "pending", updatedAt: new Date().toISOString() } : item))
    );
    setNotice("歌词已保存为 pending submission，等待管理员审核。");
  };

  useEffect(() => {
    const interval = window.setInterval(() => {
      const player = playerRef.current;
      if (!player) {
        return;
      }

      const nextTime = player.getCurrentTime();
      setCurrentTime(nextTime);

      const nextActiveLine = findActiveLine(visibleLyrics.lines, nextTime);
      setActiveLineId(nextActiveLine?.id ?? null);

      if (isLoopingLine && nextActiveLine && nextTime >= nextActiveLine.endTime - 0.05) {
        player.seekTo(nextActiveLine.startTime, true);
      }
    }, 150);

    return () => window.clearInterval(interval);
  }, [isLoopingLine, setActiveLineId, setCurrentTime, visibleLyrics.lines]);

  useEffect(() => {
    setActiveLineId(activeLine?.id ?? null);
  }, [activeLine?.id, setActiveLineId]);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.code !== "Space" || event.repeat) {
        return;
      }

      const target = event.target as HTMLElement | null;
      const isTyping =
        target?.tagName === "INPUT" ||
        target?.tagName === "TEXTAREA" ||
        target?.tagName === "SELECT" ||
        target?.isContentEditable;

      if (isTyping) {
        return;
      }

      event.preventDefault();
      if (isPlaying) {
        playerRef.current?.pauseVideo();
      } else {
        playerRef.current?.playVideo();
      }
    };

    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [isPlaying]);

  return (
    <main className="min-h-screen bg-background">
      <header className="sticky top-0 z-20 border-b bg-background/95 backdrop-blur">
        <div className="mx-auto flex h-14 max-w-[1560px] items-center gap-3 px-4">
          <Button variant="ghost" size="icon" title="Menu">
            <Menu className="h-5 w-5" />
          </Button>
          <button className="flex items-center gap-2 font-semibold" onClick={() => setActiveWorkspace("watch")}>
            <span className="grid h-8 w-8 place-items-center rounded bg-primary text-primary-foreground">
              <Mic className="h-4 w-4" />
            </span>
            UtaLoop
          </button>

          <div className="mx-auto hidden w-full max-w-2xl items-center gap-2 md:flex">
            <input
              className="h-10 min-w-0 flex-1 rounded-full border bg-background px-4 text-sm outline-none focus:ring-2 focus:ring-ring"
              value={searchQuery}
              onChange={(event) => setSearchQuery(event.target.value)}
              placeholder={copy.searchPlaceholder}
              onKeyDown={(event) => {
                if (event.key === "Enter") {
                  void searchSongs();
                }
              }}
            />
            <Button size="icon" onClick={() => void searchSongs()} title="Search songs">
              <Search className="h-4 w-4" />
            </Button>
          </div>

          <Button variant={activeWorkspace === "create" ? "default" : "outline"} onClick={() => setActiveWorkspace("create")}>
            <Upload className="h-4 w-4" />
            {copy.create}
          </Button>
          <select
            className="h-9 rounded-md border bg-background px-2 text-sm outline-none focus:ring-2 focus:ring-ring"
            value={uiLanguage}
            onChange={(event) => setUiLanguage(event.target.value as UiLanguage)}
            title="Language"
          >
            <option value="zh">中文</option>
            <option value="en">EN</option>
          </select>
          <Button variant="ghost" size="icon" title="Notifications">
            <Bell className="h-5 w-5" />
          </Button>
          {session ? (
            <div className="relative">
              <button
                className="grid h-9 w-9 place-items-center rounded-full bg-secondary text-secondary-foreground"
                onClick={() => setIsUserMenuOpen((open) => !open)}
                title="Profile"
              >
                <User className="h-4 w-4" />
              </button>
              {isUserMenuOpen ? (
                <div className="absolute right-0 top-11 z-40 w-48 rounded-md border bg-card p-1 shadow-lg">
                  <button
                    className="flex w-full items-center gap-2 rounded px-3 py-2 text-left text-sm hover:bg-muted"
                    onClick={() => {
                      setActiveWorkspace("profile");
                      setIsUserMenuOpen(false);
                    }}
                  >
                    <User className="h-4 w-4" />
                    {copy.profile}
                  </button>
                  <button
                    className="flex w-full items-center gap-2 rounded px-3 py-2 text-left text-sm hover:bg-muted"
                    onClick={() => {
                      setActiveWorkspace("my-creations");
                      setIsUserMenuOpen(false);
                    }}
                  >
                    <FolderOpen className="h-4 w-4" />
                    {copy.myCreations}
                  </button>
                  <button
                    className="flex w-full items-center gap-2 rounded px-3 py-2 text-left text-sm hover:bg-muted"
                    onClick={() => {
                      setActiveWorkspace("favorites");
                      setIsUserMenuOpen(false);
                    }}
                  >
                    <Heart className="h-4 w-4" />
                    {copy.myFavorites}
                  </button>
                  {session.role === "admin" ? (
                    <button
                      className="flex w-full items-center gap-2 rounded px-3 py-2 text-left text-sm hover:bg-muted"
                      onClick={() => {
                        setActiveWorkspace("admin");
                        setIsUserMenuOpen(false);
                      }}
                    >
                      <ShieldCheck className="h-4 w-4" />
                      {copy.review}
                    </button>
                  ) : null}
                  <button
                    className="flex w-full items-center gap-2 rounded px-3 py-2 text-left text-sm hover:bg-muted"
                    onClick={() => {
                      setSession(null);
                      setActiveWorkspace("watch");
                      setIsUserMenuOpen(false);
                    }}
                  >
                    <LogOut className="h-4 w-4" />
                    {copy.logout}
                  </button>
                </div>
              ) : null}
            </div>
          ) : (
            <Button variant="secondary" onClick={() => setActiveWorkspace("auth")}>
              <LogIn className="h-4 w-4" />
              {copy.login}
            </Button>
          )}
        </div>
      </header>

      <div className="mx-auto grid max-w-[1560px] gap-6 px-4 py-5 xl:grid-cols-[minmax(0,1fr)_390px]">
        <div className="min-w-0 space-y-4">
          {activeWorkspace === "watch" ? (
            <WatchMode
              activeLine={activeLine}
              copy={copy}
              onChangeRate={changeRate}
              onReplayLine={replayLine}
              onSeek={seekTo}
              playerRef={playerRef}
              searchResults={searchResults}
              song={activeSong}
            />
          ) : null}

          {activeWorkspace === "my-creations" ? (
            <MyCreationsPanel copy={copy} creations={myCreations} onEdit={editCreation} />
          ) : null}

          {activeWorkspace === "favorites" ? (
            <FavoritesPanel copy={copy} count={favoriteIds.length} />
          ) : null}

          {activeWorkspace === "create" ? (
            <CreateMode
              captionLanguages={captionLanguages}
              copy={copy}
              createVideo={createVideo}
              createVideoUrl={createVideoUrl}
              createMeta={createMeta}
              draftLyrics={draftLyrics}
              editorLyrics={editorLyrics}
              currentTime={currentTime}
              isFetchingLanguages={isFetchingLanguages}
              isFetchingSubtitles={isFetchingSubtitles}
              isAutoAligning={isAutoAligning}
              onChangeRate={changeRate}
              onCreateVideoUrlChange={setCreateVideoUrl}
              onCreateMetaChange={setCreateMeta}
              onFetchCaptions={fetchYouTubeSubtitles}
              onAutoAlign={autoAlign}
              onDeleteLine={deleteLyricLine}
              onInsertLine={insertLyricLine}
              onLineDurationChange={changeLineDuration}
              onLineStartChange={changeLineStart}
              onGlobalNudge={nudgeAllLines}
              onImportLyrics={importLyrics}
              onLoadVideo={loadCreateVideo}
              onReplayLine={replayLine}
              onSeek={seekTo}
              onSubmit={submitLyrics}
              onSaveLyrics={saveEditedLyrics}
              onWordDurationNudge={nudgeWordDuration}
              onWordStartNudge={nudgeWordStart}
              onSubtitleLangChange={setSubtitleLang}
              playerRef={playerRef}
              subtitleLang={subtitleLang}
              subtitleText={subtitleText}
              onSubtitleTextChange={updateSubtitleText}
              activeLine={activeLine}
              videoDuration={playerDuration}
            />
          ) : null}

          {activeWorkspace === "auth" ? (
            <AuthPanel
              authMode={authMode}
              copy={copy}
              onAuthModeChange={setAuthMode}
              onSignedIn={(user) => {
                setSession(user);
                setError(null);
                setActiveWorkspace("profile");
              }}
            />
          ) : null}

          {activeWorkspace === "profile" ? (
            <ProfilePanel
              copy={copy}
              session={session}
              onAdminOpen={() => setActiveWorkspace("admin")}
              onSignOut={() => {
                setSession(null);
                setActiveWorkspace("watch");
              }}
              onAuthOpen={() => setActiveWorkspace("auth")}
            />
          ) : null}

          {activeWorkspace === "admin" ? (
            <AdminReviewPanel
              copy={copy}
              creations={myCreations}
              session={session}
              onApprove={(id) => {
                setMyCreations((items) =>
                  items.map((item) => (item.id === id ? { ...item, status: "approved" } : item))
                );
                setSearchResults((items) => {
                  const approved = myCreations.find((item) => item.id === id);
                  return approved ? [creationToSong({ ...approved, status: "approved" }), ...items] : items;
                });
              }}
              onReject={(id) =>
                setMyCreations((items) =>
                  items.map((item) => (item.id === id ? { ...item, status: "rejected" } : item))
                )
              }
            />
          ) : null}

          {error ? <StatusTone tone="error" text={error} /> : null}
          {notice ? <StatusTone tone="success" text={notice} /> : null}
        </div>

        <SongSidebar
          copy={copy}
          songs={searchResults}
          onSongSelect={chooseSong}
          session={session}
          onAuthOpen={() => setActiveWorkspace("auth")}
        />
      </div>
    </main>
  );
}

function WatchMode({
  activeLine,
  copy,
  onChangeRate,
  onReplayLine,
  onSeek,
  playerRef,
  searchResults,
  song
}: {
  activeLine: LyricLine | null;
  copy: typeof COPY[UiLanguage];
  onChangeRate: (rate: number) => void;
  onReplayLine: () => void;
  onSeek: (time: number) => void;
  playerRef: React.MutableRefObject<YT.Player | null>;
  searchResults: SongVideo[];
  song: SongVideo;
}) {
  return (
    <>
      <VideoSurface
        video={song.video}
        onReady={(player) => {
          playerRef.current = player;
        }}
      />

      <section className="space-y-3">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <h1 className="text-xl font-semibold">{song.title}</h1>
            <div className="mt-1 flex flex-wrap items-center gap-2 text-sm text-muted-foreground">
              <span>{song.artist}</span>
              <span>{song.language}</span>
              <span>{song.views} views</span>
              <span>lyrics by {song.creator}</span>
            </div>
          </div>
          <a
            className="inline-flex h-10 items-center gap-2 rounded-md border px-3 text-sm font-medium hover:bg-muted"
            href={song.sourceUrl}
            rel="noreferrer"
            target="_blank"
          >
            <ExternalLink className="h-4 w-4" />
            {copy.source}: {song.sourceLabel}
          </a>
        </div>

        <PlaybackControls
          activeLineStart={activeLine?.startTime}
          onPause={() => playerRef.current?.pauseVideo()}
          onPlay={() => playerRef.current?.playVideo()}
          onReplayLine={onReplayLine}
          onRateChange={onChangeRate}
        />
      </section>

      <section className="rounded-lg border bg-card p-4 shadow-sm">
        <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            <Captions className="h-5 w-5 text-primary" />
            <h2 className="text-lg font-semibold">{copy.lyrics}</h2>
          </div>
          <LyricsDownload fileName={song.title} labels={{ download: copy.download, format: copy.format }} lines={song.lyrics.lines} />
        </div>
        <div className="h-[380px]">
          <LyricsScroller lines={song.lyrics.lines} onSeek={onSeek} />
        </div>
      </section>

      <CommentsPanel copy={copy} song={song} />

      {searchResults.length === 0 ? (
        <section className="rounded-lg border bg-card p-4 text-sm text-muted-foreground shadow-sm">
          {copy.noResults}
        </section>
      ) : null}
    </>
  );
}

function CreateMode({
  activeLine,
  captionLanguages,
  copy,
  createVideo,
  createVideoUrl,
  createMeta,
  currentTime,
  draftLyrics,
  editorLyrics,
  isFetchingLanguages,
  isFetchingSubtitles,
  isAutoAligning,
  onChangeRate,
  onAutoAlign,
  onCreateMetaChange,
  onCreateVideoUrlChange,
  onDeleteLine,
  onFetchCaptions,
  onGlobalNudge,
  onInsertLine,
  onImportLyrics,
  onLineDurationChange,
  onLineStartChange,
  onLoadVideo,
  onReplayLine,
  onSeek,
  onSubmit,
  onSaveLyrics,
  onSubtitleLangChange,
  onSubtitleTextChange,
  onWordDurationNudge,
  onWordStartNudge,
  playerRef,
  subtitleLang,
  subtitleText,
  videoDuration
}: {
  activeLine: LyricLine | null;
  captionLanguages: CaptionLanguage[];
  copy: typeof COPY[UiLanguage];
  createVideo: ResolvedVideo | null;
  createVideoUrl: string;
  createMeta: CreationMeta;
  currentTime: number;
  draftLyrics: ParsedLyrics;
  editorLyrics: ParsedLyrics;
  isFetchingLanguages: boolean;
  isFetchingSubtitles: boolean;
  isAutoAligning: boolean;
  onChangeRate: (rate: number) => void;
  onAutoAlign: () => void;
  onCreateMetaChange: (meta: CreationMeta) => void;
  onCreateVideoUrlChange: (value: string) => void;
  onDeleteLine: (lineId: string) => void;
  onFetchCaptions: () => void;
  onGlobalNudge: (delta: number) => void;
  onInsertLine: (time: number) => void;
  onImportLyrics: () => void;
  onLineDurationChange: (lineId: string, duration: number) => void;
  onLineStartChange: (lineId: string, startTime: number) => void;
  onLoadVideo: () => void;
  onReplayLine: () => void;
  onSeek: (time: number) => void;
  onSubmit: () => void;
  onSaveLyrics: () => void;
  onSubtitleLangChange: (value: string) => void;
  onSubtitleTextChange: (value: string) => void;
  onWordDurationNudge: (lineId: string, wordId: string, delta: number) => void;
  onWordStartNudge: (lineId: string, wordId: string, delta: number) => void;
  playerRef: React.MutableRefObject<YT.Player | null>;
  subtitleLang: string;
  subtitleText: string;
  videoDuration: number;
}) {
  return (
    <>
      <section className="rounded-lg border bg-card p-4 shadow-sm">
        <h1 className="text-xl font-semibold">{copy.createMode}</h1>
        <div className="mt-3 grid gap-2 md:grid-cols-2">
          <input
            className="h-10 rounded-md border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
            value={createMeta.title}
            onChange={(event) => onCreateMetaChange({ ...createMeta, title: event.target.value })}
            placeholder={copy.songTitle}
          />
          <input
            className="h-10 rounded-md border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
            value={createMeta.artist}
            onChange={(event) => onCreateMetaChange({ ...createMeta, artist: event.target.value })}
            placeholder={copy.artist}
          />
          <input
            className="h-10 rounded-md border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
            value={createMeta.language}
            onChange={(event) => onCreateMetaChange({ ...createMeta, language: event.target.value })}
            placeholder={copy.language}
          />
          <input
            className="h-10 rounded-md border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
            value={createMeta.description}
            onChange={(event) => onCreateMetaChange({ ...createMeta, description: event.target.value })}
            placeholder={copy.description}
          />
        </div>
        <div className="mt-3 grid gap-2 md:grid-cols-[minmax(0,1fr)_auto]">
          <input
            className="h-10 rounded-md border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
            value={createVideoUrl}
            onChange={(event) => onCreateVideoUrlChange(event.target.value)}
            placeholder={copy.sourceUrl}
          />
          <Button onClick={onLoadVideo}>
            <Film className="h-4 w-4" />
            {copy.sourceVideo}
          </Button>
        </div>
      </section>

      <VideoSurface
        video={createVideo}
        onReady={(player) => {
          playerRef.current = player;
        }}
      />

      <section className="space-y-3 rounded-lg border bg-card p-4 shadow-sm">
        <div className="flex flex-wrap gap-2">
          <select
            className="h-10 rounded-md border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
            value={subtitleLang}
            onChange={(event) => onSubtitleLangChange(event.target.value)}
            disabled={createVideo?.platform !== "youtube" || isFetchingLanguages}
            title="Caption language"
          >
            {captionLanguages.length === 0 ? (
              <option value="">{isFetchingLanguages ? "Loading captions" : "No caption list"}</option>
            ) : (
              captionLanguages.map((language) => (
                <option key={language.code} value={language.code}>
                  {language.name} ({language.code}){language.isAutoGenerated ? " auto" : ""}
                </option>
              ))
            )}
          </select>
          <Button
            variant="secondary"
            onClick={onFetchCaptions}
            disabled={createVideo?.platform !== "youtube" || isFetchingSubtitles}
          >
            <Download className="h-4 w-4" />
            {isFetchingSubtitles ? copy.fetching : copy.fetchCaptions}
          </Button>
          <Button variant="outline" onClick={onAutoAlign} disabled={isAutoAligning}>
            <Wand2 className="h-4 w-4" />
            {isAutoAligning ? copy.aligning : copy.autoAlign}
          </Button>
        </div>

        <PlaybackControls
          activeLineStart={activeLine?.startTime}
          onPause={() => playerRef.current?.pauseVideo()}
          onPlay={() => playerRef.current?.playVideo()}
          onReplayLine={onReplayLine}
          onRateChange={onChangeRate}
        />
      </section>

      <LyricTimeline
        currentTime={currentTime}
        lines={editorLyrics.lines}
        onDeleteLine={onDeleteLine}
        onInsertLine={onInsertLine}
        onLineDurationChange={onLineDurationChange}
        onLineStartChange={onLineStartChange}
        onSeek={onSeek}
        videoDuration={videoDuration}
      />

      <section className="rounded-lg border bg-card p-4 shadow-sm">
        <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
          <div className="flex items-center gap-2">
            <Captions className="h-5 w-5 text-primary" />
            <h2 className="text-lg font-semibold">{copy.calibrationPreview}</h2>
          </div>
          <LyricsDownload
            fileName={createMeta.title || "draft-lyrics"}
            labels={{ download: copy.download, format: copy.format }}
            lines={draftLyrics.lines}
          />
        </div>
        <div className="h-[300px]">
          <LyricsScroller lines={draftLyrics.lines} onSeek={onSeek} />
        </div>
      </section>

      <CreatorPanel
        currentTime={currentTime}
        lines={editorLyrics.lines}
        onGlobalNudge={onGlobalNudge}
        onImport={onImportLyrics}
        onSave={onSaveLyrics}
        onSeek={onSeek}
        onWordDurationNudge={onWordDurationNudge}
        onWordStartNudge={onWordStartNudge}
        subtitleText={subtitleText}
        onSubtitleTextChange={onSubtitleTextChange}
      />

      <section className="rounded-lg border bg-card p-4 shadow-sm">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <h2 className="text-lg font-semibold">{copy.submitReview}</h2>
            <p className="text-sm text-muted-foreground">{copy.submitSavedVersion}</p>
          </div>
          <Button onClick={onSubmit} disabled={draftLyrics.lines.length === 0}>
            <Send className="h-4 w-4" />
            {copy.submitForReview}
          </Button>
        </div>
      </section>
    </>
  );
}

function AuthPanel({
  authMode,
  copy,
  onAuthModeChange,
  onSignedIn
}: {
  authMode: "login" | "register";
  copy: typeof COPY[UiLanguage];
  onAuthModeChange: (mode: "login" | "register") => void;
  onSignedIn: (user: UserSession) => void;
}) {
  const [displayName, setDisplayName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [authError, setAuthError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const submit = async () => {
    setIsSubmitting(true);
    setAuthError(null);

    try {
      const response = await fetch(`/api/auth/${authMode}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ displayName, email, password })
      });
      const payload = await response.json();
      if (!response.ok) {
        throw new Error(payload.message ?? "Authentication failed");
      }
      onSignedIn(payload.user);
    } catch (error) {
      setAuthError(error instanceof Error ? error.message : "Authentication failed");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <section className="mx-auto max-w-md rounded-lg border bg-card p-5 shadow-sm">
      <div className="mb-4 flex items-center gap-2">
        <UserPlus className="h-5 w-5 text-primary" />
        <h1 className="text-xl font-semibold">{authMode === "login" ? copy.login : "Register"}</h1>
      </div>
      <div className="space-y-3">
        {authMode === "register" ? (
          <input
            className="h-10 w-full rounded-md border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
            value={displayName}
            onChange={(event) => setDisplayName(event.target.value)}
            placeholder="Display name"
          />
        ) : null}
        <input
          className="h-10 w-full rounded-md border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
          value={email}
          onChange={(event) => setEmail(event.target.value)}
          placeholder="Email"
          type="email"
        />
        <input
          className="h-10 w-full rounded-md border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring"
          value={password}
          onChange={(event) => setPassword(event.target.value)}
          placeholder="Password"
          type="password"
        />
        {authError ? <StatusTone tone="error" text={authError} /> : null}
        <Button className="w-full" onClick={submit} disabled={isSubmitting}>
          <LogIn className="h-4 w-4" />
          {isSubmitting ? "Submitting" : authMode === "login" ? copy.login : "Create account"}
        </Button>
        <Button
          className="w-full"
          variant="ghost"
          onClick={() => onAuthModeChange(authMode === "login" ? "register" : "login")}
        >
          {authMode === "login" ? "Need an account?" : "Already have an account?"}
        </Button>
      </div>
    </section>
  );
}

function SongSidebar({
  copy,
  onAuthOpen,
  onSongSelect,
  session,
  songs
}: {
  copy: typeof COPY[UiLanguage];
  onAuthOpen: () => void;
  onSongSelect: (song: SongVideo) => void;
  session: UserSession | null;
  songs: SongVideo[];
}) {
  return (
    <aside className="space-y-3">
      <div className="rounded-lg border bg-card p-3 shadow-sm">
        <div className="mb-3 flex items-center justify-between">
          <h2 className="font-semibold">{copy.siteSongs}</h2>
          <Film className="h-4 w-4 text-muted-foreground" />
        </div>
        <div className="space-y-3">
          {songs.map((song) => (
            <button
              key={song.id}
              className="grid w-full grid-cols-[132px_minmax(0,1fr)] gap-3 text-left"
              onClick={() => onSongSelect(song)}
            >
              <div className="aspect-video rounded-md bg-muted" />
              <div className="min-w-0">
                <p className="line-clamp-2 text-sm font-medium">{song.title}</p>
                <p className="mt-1 text-xs text-muted-foreground">{song.artist}</p>
                <p className="text-xs text-muted-foreground">{song.sourceLabel} · {song.views} views</p>
              </div>
            </button>
          ))}
        </div>
      </div>

      <div className="rounded-lg border bg-card p-3 shadow-sm">
        <h2 className="font-semibold">{copy.account}</h2>
        <div className="mt-3">
          {session ? (
            <div className="flex items-center gap-3">
              <div className="grid h-9 w-9 place-items-center rounded-full bg-secondary">
                <User className="h-4 w-4" />
              </div>
              <div className="min-w-0">
                <p className="truncate text-sm font-medium">{session.displayName}</p>
                <p className="text-xs text-muted-foreground">{session.role}</p>
              </div>
            </div>
          ) : (
            <Button className="w-full" variant="outline" onClick={onAuthOpen}>
              <UserPlus className="h-4 w-4" />
              {copy.loginRegister}
            </Button>
          )}
        </div>
      </div>
    </aside>
  );
}

function MyCreationsPanel({
  copy,
  creations,
  onEdit
}: {
  copy: typeof COPY[UiLanguage];
  creations: CreationEntry[];
  onEdit: (creation: CreationEntry) => void;
}) {
  return (
    <section className="rounded-lg border bg-card p-4 shadow-sm">
      <h1 className="text-xl font-semibold">{copy.myCreations}</h1>
      <div className="mt-4 space-y-2">
        {creations.length === 0 ? (
          <p className="text-sm text-muted-foreground">{copy.noCreations}</p>
        ) : (
          creations.map((creation) => (
            <div key={creation.id} className="grid gap-3 rounded-md border p-3 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center">
              <div>
                <p className="font-medium">{creation.meta.title}</p>
                <p className="text-sm text-muted-foreground">
                  {creation.meta.artist || "Unknown artist"} · {creation.meta.language || "Unknown language"} · {creation.status}
                </p>
              </div>
              <Button variant="outline" onClick={() => onEdit(creation)}>
                {copy.edit}
              </Button>
            </div>
          ))
        )}
      </div>
    </section>
  );
}

function FavoritesPanel({ copy, count }: { copy: typeof COPY[UiLanguage]; count: number }) {
  return (
    <section className="rounded-lg border bg-card p-4 shadow-sm">
      <h1 className="text-xl font-semibold">{copy.myFavorites}</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        {copy.myFavorites}: {count}. {copy.favoritesEmpty}
      </p>
    </section>
  );
}

function StatusTone({ text, tone }: { text: string; tone: "error" | "success" }) {
  return (
    <div
      className={cn(
        "rounded-md border px-3 py-2 text-sm",
        tone === "error"
          ? "border-destructive/40 bg-destructive/10 text-destructive"
          : "border-primary/30 bg-primary/10 text-primary"
      )}
    >
      {text}
    </div>
  );
}

function CommentsPanel({ copy, song }: { copy: typeof COPY[UiLanguage]; song: SongVideo }) {
  return (
    <section className="rounded-lg border bg-card p-4 shadow-sm">
      <h2 className="text-lg font-semibold">{copy.comments}</h2>
      <div className="mt-4 flex gap-3">
        <div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-secondary">
          <User className="h-4 w-4" />
        </div>
        <input
          className="h-10 flex-1 border-b bg-transparent text-sm outline-none focus:border-primary"
          placeholder={`Comment on ${song.title}`}
        />
      </div>
      <div className="mt-5 space-y-4">
        <Comment author="kana" text="单句循环很适合练副歌，下一步想要罗马音和假名双行。" />
        <Comment author="admin" text="审核通过后的歌词会进入公共库，普通用户也可以保留私人版本。" />
      </div>
    </section>
  );
}

function Comment({ author, text }: { author: string; text: string }) {
  return (
    <div className="flex gap-3">
      <div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-muted text-xs font-semibold">
        {author.slice(0, 1).toUpperCase()}
      </div>
      <div>
        <p className="text-sm font-medium">{author}</p>
        <p className="text-sm text-muted-foreground">{text}</p>
      </div>
    </div>
  );
}

function ProfilePanel({
  copy,
  onAdminOpen,
  onAuthOpen,
  onSignOut,
  session
}: {
  copy: typeof COPY[UiLanguage];
  onAdminOpen: () => void;
  onAuthOpen: () => void;
  onSignOut: () => void;
  session: UserSession | null;
}) {
  if (!session) {
    return (
      <section className="rounded-lg border bg-card p-4 shadow-sm">
        <h1 className="text-xl font-semibold">Profile</h1>
        <p className="mt-1 text-sm text-muted-foreground">{copy.profileHint}</p>
        <Button className="mt-4" onClick={onAuthOpen}>
          <LogIn className="h-4 w-4" />
          {copy.loginRegister}
        </Button>
      </section>
    );
  }

  return (
    <section className="rounded-lg border bg-card p-4 shadow-sm">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <div className="grid h-14 w-14 place-items-center rounded-full bg-secondary">
            <User className="h-6 w-6" />
          </div>
          <div>
            <h2 className="text-lg font-semibold">{session.displayName}</h2>
            <p className="text-sm text-muted-foreground">{session.email} · {session.role}</p>
          </div>
        </div>
        <div className="flex gap-2">
          <Button variant="secondary" onClick={onAdminOpen} disabled={session.role !== "admin"}>
            <ShieldCheck className="h-4 w-4" />
            Review
          </Button>
          <Button variant="outline" onClick={onSignOut}>Sign out</Button>
        </div>
      </div>
    </section>
  );
}

function AdminReviewPanel({
  copy,
  creations,
  onApprove,
  onReject,
  session
}: {
  copy: typeof COPY[UiLanguage];
  creations: CreationEntry[];
  onApprove: (id: string) => void;
  onReject: (id: string) => void;
  session: UserSession | null;
}) {
  if (session?.role !== "admin") {
    return (
      <section className="rounded-lg border bg-card p-4 shadow-sm">
        <StatusTone tone="error" text={copy.adminOnly} />
      </section>
    );
  }

  return (
    <section className="rounded-lg border bg-card p-4 shadow-sm">
      <div className="mb-3 flex items-center gap-2">
        <ShieldCheck className="h-5 w-5 text-primary" />
        <h2 className="text-lg font-semibold">{copy.adminReview}</h2>
      </div>
      <div className="space-y-2">
        {creations.filter((item) => item.status === "pending").length === 0 ? (
          <p className="text-sm text-muted-foreground">{copy.noPending}</p>
        ) : (
          creations
            .filter((item) => item.status === "pending")
            .map((item) => (
              <div key={item.id} className="grid gap-3 rounded-md border p-3 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center">
                <div>
                  <p className="font-medium">{item.meta.title}</p>
                  <p className="text-sm text-muted-foreground">
                    {item.meta.artist || "Unknown artist"} · {item.meta.language || "Unknown language"} · {item.status}
                  </p>
                </div>
                <div className="flex gap-2">
                  <Button variant="outline" onClick={() => onReject(item.id)}>
                    <XCircle className="h-4 w-4" />
                    {copy.reject}
                  </Button>
                  <Button onClick={() => onApprove(item.id)}>
                    <CheckCircle2 className="h-4 w-4" />
                    {copy.approve}
                  </Button>
                </div>
              </div>
            ))
        )}
      </div>
    </section>
  );
}

function findActiveLine(lines: LyricLine[], time: number) {
  return lines.find((line) => time >= line.startTime && time < line.endTime) ?? null;
}

function normalizeMeta(meta: CreationMeta, video: ResolvedVideo): CreationMeta {
  return {
    title: meta.title.trim() || `${video.platform} ${video.videoId}`,
    artist: meta.artist.trim() || "Unknown artist",
    language: meta.language.trim() || "Unknown",
    description: meta.description.trim()
  };
}

function creationToSong(creation: CreationEntry): SongVideo {
  return {
    id: `creation-${creation.id}`,
    title: creation.meta.title,
    artist: creation.meta.artist,
    language: creation.meta.language,
    sourceUrl: creation.sourceUrl,
    sourceLabel: creation.video.platform === "youtube" ? "YouTube" : "Bilibili",
    creator: "Me",
    views: creation.status,
    video: creation.video,
    lyrics: creation.lyrics
  };
}

function shiftLineTiming(line: LyricLine, delta: number): LyricLine {
  const startTime = Math.max(0, line.startTime + delta);
  const endTime = Math.max(startTime + 0.2, line.endTime + delta);

  return {
    ...line,
    startTime,
    endTime,
    words: line.words.map((word) => ({
      ...word,
      startTime: Math.max(0, word.startTime + delta),
      endTime: Math.max(0.2, word.endTime + delta)
    }))
  };
}

function moveLineToStart(line: LyricLine, nextStartTime: number): LyricLine {
  const delta = Math.max(0, nextStartTime) - line.startTime;
  return shiftLineTiming(line, delta);
}

function setLineDuration(line: LyricLine, duration: number): LyricLine {
  const nextDuration = Math.max(0.2, duration);
  const previousDuration = Math.max(0.2, line.endTime - line.startTime);

  return {
    ...line,
    endTime: line.startTime + nextDuration,
    words: line.words.map((word) => {
      const startRatio = (word.startTime - line.startTime) / previousDuration;
      const endRatio = (word.endTime - line.startTime) / previousDuration;
      return {
        ...word,
        startTime: line.startTime + nextDuration * startRatio,
        endTime: line.startTime + nextDuration * endRatio
      };
    })
  };
}

function makeInsertedLine(id: string, startTime: number): LyricLine {
  const safeStart = Math.max(0, startTime);
  const text = "New lyric";
  return {
    id,
    startTime: safeStart,
    endTime: safeStart + 2,
    text,
    words: [
      {
        id: `${id}-word-1`,
        text,
        startTime: safeStart,
        endTime: safeStart + 2
      }
    ]
  };
}

function shiftWordTiming(line: LyricLine, wordId: string, delta: number): LyricLine {
  return {
    ...line,
    words: line.words.map((word) => {
      if (word.id !== wordId) {
        return word;
      }

      const duration = Math.max(0.05, word.endTime - word.startTime);
      const startTime = clamp(word.startTime + delta, line.startTime, line.endTime - 0.05);
      return {
        ...word,
        startTime,
        endTime: Math.min(line.endTime, startTime + duration)
      };
    })
  };
}

function resizeWordDuration(line: LyricLine, wordId: string, delta: number): LyricLine {
  return {
    ...line,
    words: line.words.map((word) => {
      if (word.id !== wordId) {
        return word;
      }

      const duration = Math.max(0.05, word.endTime - word.startTime + delta);
      return {
        ...word,
        endTime: Math.min(line.endTime, word.startTime + duration)
      };
    })
  };
}

function clamp(value: number, min: number, max: number) {
  return Math.min(max, Math.max(min, value));
}

function toLrcText(lines: LyricLine[]) {
  return lines.map((line) => `[${formatLrcTime(line.startTime)}]${line.text}`).join("\n");
}

function formatLrcTime(totalSeconds: number) {
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = Math.floor(totalSeconds % 60);
  const hundredths = Math.floor((totalSeconds % 1) * 100);

  return `${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}.${String(hundredths).padStart(2, "0")}`;
}
